#!/bin/bash
#
# ParameterWeaver: a code generator to handle command line parameters
# and configuration files for C/C++/Fortran/R/Octave
# Copyright (C) 2013 Geert Jan Bex <geertjan.bex@uhasselt.be>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

case "${VSC_INSTITUTE_CLUSTER}" in
    vic3)
        . /apps/leuven/etc/bash.bashrc
        module purge
        module load python/2.7.1
        module load gcc/4.6.2
        module load R/2.14.2
        ;;
    thinking)
        module purge
        module load thinking/2014a
        module load Python/2.7.6-foss-2014a
        module load R/2.15.3-foss-2014a-default
        ;;
esac

python -m unittest discover -p '*_test.py'

